# Synth Wave (Purple)
# Retro synth purples — vaporwave aesthetics
[custom_themes.synth_wave]
blue         = 91
green        = 177
purple       = 128
light_purple = 134
royal        = 93
dark_purple  = 97
